### PR TITLE
test(GCP): Add remaining GCP tests for KMS checks

### PR DESCRIPTION
**Pull request by danibarranqueroo**
### Context

There was some checks without tests for KMS in GCP provider.

### Description

Added new tests for the following checks:

- [x] `kms_key_not_publicly_accessible check`
- [x] `kms_key_rotation_enabled check`

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by danibarranqueroo** [comment]
The GitHub checks failed because there was an existing AWS KMS test with the same name as this new GCP KMS test. I’ve changed the name of the GCP KMS `kms_key_not_publicly_accessible` check and test to `kms_key_not_public_access`, and it should work correctly now.

**Comment by jfagoagas** [comment]
> The GitHub checks failed because there was an existing AWS KMS test with the same name as this new GCP KMS test. I’ve changed the name of the GCP KMS `kms_key_not_publicly_accessible` check and test to `kms_key_not_public_access`, and it should work correctly now.

I think you can also rename the test class file with something else to avoid this and be able to have the same check name for both providers. I think is only an issue with how `pytest` looks for test files. There should be some similar already addressed cases for IAM.

**Comment by danibarranqueroo** [comment]
Hi @jfagoagas!
I’ve followed your suggestions and updated the names accordingly. I kept the old name for the check and only changed the test file and class names by adding "gcp" to avoid pytest failures.

**Review by MrCloudSec — APPROVED** [review]
Great job @danibarranqueroo !

**Pull request merged**
