### PR TITLE
feat(prowler-docker): Run Prowler docker with AWS SSO

### PR DESCRIPTION
**Pull request by Twodragon0**
### Context
This pull request addresses the issues encountered when running Prowler in a Docker container. Specifically, it fixes the incorrect usage of output flags that led to ambiguous option errors and enhances the script by adding a local web server to host the Prowler dashboard for easier access and monitoring.

### Description
Fixed Output Flags: Corrected the Prowler Docker command by separating output formats into individual -M flags (html, csv, json-ocsf) to eliminate ambiguity and ensure proper report generation.
Output Directory and Filename: Replaced the ambiguous --output flag with --output-directory and --output-filename to clearly specify where and how the reports are saved.
Local Web Server Integration: Added functionality to start a Python-based local HTTP server that hosts the Prowler dashboard at http://localhost:8000, allowing users to access the reports via a web browser.
Browser Automation: Implemented automatic opening of the generated HTML report in the default web browser after the script execution for immediate review.
Environment Variable Handling: Ensured that AWS credentials are correctly exported and passed to the Docker container by properly quoting variables, preventing potential issues with paths containing spaces or special characters.
Dependencies:
Python 3: Required for running the local HTTP server.
jq: Utilized for parsing JSON responses from AWS CLI commands.

### Checklist
Are there new checks included in this PR? Yes
If so, do we need to update permissions for the provider? Please review this carefully.
 Review if the code is being covered by tests.
 Review if code is being documented following this specification [Google Python Style Guide](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings)
 Review if backport is needed.

### License
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jfagoagas — APPROVED** [review]
Hello @Twodragon0, could you please move the folder `util/aws-sso-docker` to `contrib/aws-sso-docker` since this is the place where we store all the scripts and contributions to run Prowler.

Thanks for contributing to Prowler 🚀

**Review by jfagoagas — DISMISSED** [review]
I misclicked the button, I wanted to request changes -> https://github.com/prowler-cloud/prowler/pull/5867#pullrequestreview-2460625075

**Review by Twodragon0 — COMMENTED** [review]
Thank you for your comment. 
modify location ( util/ -> contrib/ )

**Review by pedrooot — CHANGES_REQUESTED** [review]
Hey @Twodragon0 this looks great. As a final request, I’d like you to move all these changes into the `/contrib/aws` directory since they are related to AWS. Thank you very much, and sorry for the inconvenience 🚀

**Comment by pedrooot** [comment]
Hey! @Twodragon0 I'll make the changes for you! Thanks.

**Review by pedrooot — APPROVED** [review]
🔝 Thanks for this @Twodragon0

**Comment by Twodragon0** [comment]
Thank you so much!

**Pull request merged**
