### PR TITLE
fix(cis): update CIS AWS v2.0 Section 2.1 refs

### PR DESCRIPTION
**Pull request by strawp**
### Context

Fixed a couple of reference numbers that were wrong for CIS AWS v2.0

### Description

Changed ref 2.1.4 -> 2.1.3, ref 2.1.5 -> 2.1.4

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by MrCloudSec** [comment]
Good catch @strawp , the issue here is that 2.1.1 does not exist on this version. Can you eliminate it?

**Comment by MrCloudSec** [comment]
It would be 2.1.3 -> 2.1.2 and 2.1.2 -> 2.1.1. Thanks!

**Comment by strawp** [comment]
Yes, I've decided to script some checks against the CIS PDF so I'll check everything and then adjust accordingly. These two were just ones I spotted because I'd reported on them

**Comment by MrCloudSec** [comment]
Awesome @strawp , I have updated the PR with the required changes of the Section 2.1 that we mentioned. Feel free to open PRs if there are more adjusts needed from the CIS. Thanks!

**Review by MrCloudSec — APPROVED** [review]

**Comment by strawp** [comment]
Nice one, thanks! I looked through everything else and didn't spot any other mismatches

**Pull request merged**
