### PR TITLE
feat(aws): add new check `organizations_opt_out_ai_services_policy`

### PR DESCRIPTION
**Pull request by MrCloudSec**
### Context

By default, AWS may be using your data to train its AI models. This may include data from your AWS CloudTrail logs, AWS Config rules, and AWS GuardDuty findings.
### Description

Create a new check `organizations_opt_out_ai_services_policy` to ensure that AWS Organizations opt-out of AI services policy is enabled, not granting consent for AWS to access the data.
### Checklist

- Are there new checks included in this PR? Yes / No
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [x] Review if the code is being covered by tests.
- [x] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [x] Review if backport is needed.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by MrCloudSec** [comment]
DO NOT MERGE until #5151 is merged.

**Review by pedrooot — CHANGES_REQUESTED** [review]
Could you add a test to see the behaviour of this check with a policy with no content? 🙏🏼

**Comment by MrCloudSec** [comment]
> Could you add a test to see the behaviour of this check with a policy with no content? 🙏🏼

Done!

**Review by pedrooot — APPROVED** [review]
TOP 🐐

**Pull request merged**
