### PR TITLE
docs: Update `contact.md` with new Slack join URL

### PR DESCRIPTION
**Pull request by metahertz**
### Context

Update the community slack link to the new slack invitation url https://goto.prowler.com/slack 

Does not fix a raised issue, just housekeeping.

### Description

Single Docs URL change for the contact.md page.

### Checklist

- Are there new checks included in this PR?  No
- [N/A] Review if the code is being covered by tests.
- [N/A] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [N/A] Review if backport is needed.

### License
No licence changes.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jfagoagas — CHANGES_REQUESTED** [review]
Can you also update the README? Thanks!

**Comment by MrCloudSec** [comment]
> Can you also update the README? Thanks!

and in the `developer-guide/introduction.md`, please!

**Review by jfagoagas — DISMISSED** [review]

**Comment by metahertz** [comment]
Squashed commits to one change, all references replaced. Confirmed with recursive grep for `join.slack`.

**Review by jfagoagas — APPROVED** [review]
Thank you @metahertz !!

**Pull request merged**
