### PR TITLE
New Check 7157 API Gateway V2 has Configured Authorizers @qumei

### PR DESCRIPTION
**Pull request by zqumei0**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by toniblyx** [comment]
Hi @zqumei0 could you please review my comment above? Thanks!

**Comment by zqumei0** [comment]
Hi @toniblyx, not sure if I maybe missed it, but I don't see any comment above. Can you repost the comment? Thank you!

**Comment by toniblyx** [comment]
Everything looks fine but `apigateway` is the proper servicename regardless the version.

**Comment by zqumei0** [comment]
Fixed the servicename to apigateway and grammar of fail text. Let me know if you need anything else updated.

**Comment by toniblyx** [comment]
Thanks @zqumei0!!

**Pull request merged**
