### PR TITLE
feat(compliance): add KISA ISMS-P compliance framework

### PR DESCRIPTION
**Pull request by Jude-Bae**
- Added support for KISA ISMS-P to Prowler.

- Provided both English and Korean versions for broader accessibility.

### Context

This PR aims to add one of Korea’s key security compliance frameworks, the Personal Information & Information Security Management System (ISMS-P) from the Korea Internet & Security Agency (KISA), to the Prowler Compliance list.

The KISA ISMS-P is a certification system that assesses and certifies the adequacy of information security and personal information protection management systems. Many companies in Korea consider compliance with and certification through ISMS-P essential for their operations.

While Prowler is already an excellent tool, I know that there are many users in Korea as well. In particular, there has been a strong demand for KISA ISMS-P compliance, which is mandatory for companies of a certain size in Korea, and is also widely used by others. 
To address this need, I collaborated with my fellow team members from the Cloud Governance Architect Team and the Security Group at MegazoneCloud (https://www.megazone.com/us) on this contribution. We hope that this contribution will benefit Prowler users in Korea and help more people discover the value of Prowler.

Additionally, the KISA ISMS-P for Prowler will be provided in two versions: a default English version and a Korean version tailored for Korean users.

“Powered by the Cloud Governance Architect Team, in collaboration with the Cloud Security Group within the Cloud Technology Center at MegazoneCloud.”

Co-authored-by: ES Kim <es.kim@megazone.com> and Yenn <yenn@megazone.com>
- ES Kim: Contributed to the overall development and implementation of the project.
- Yenn: Assisted with code development and conducted research on ISMS-P compliance requirements.

### Description

A total of 12 files were changed, with 9,097 lines of code inserted. The changes include the addition of both the English and Korean versions of KISA ISMS-P for AWS compliance.
The following files have been added or modified:

Dashboard Integration:
dashboard/compliance/kisa_isms-p_2023-korean_aws.py
dashboard/compliance/kisa_isms-p_2023_aws.py

Compliance Files:
prowler/compliance/aws/kisa_isms-p_2023-korean_aws.json
prowler/compliance/aws/kisa_isms-p_2023_aws.json

Output and Model Files:
prowler/lib/outputs/compliance/kisa_ismsp/__init__.py
prowler/lib/outputs/compliance/kisa_ismsp/kisa_ismsp.py
prowler/lib/outputs/compliance/kisa_ismsp/kisa_ismsp_aws.py
prowler/lib/outputs/compliance/kisa_ismsp/models.py

KISA ISMS-P related updates to existing files:
prowler/__main__.py: Added KISA ISMS-P related logic to Prowler's main execution file.
prowler/lib/check/compliance_models.py: Added KISA ISMS-P related data to the compliance models file.
prowler/lib/outputs/compliance/compliance.py: Added code to handle KISA ISMS-P outputs.
dashboard/common_methods.py: Defined additional common methods to process KISA ISMS-P data.

### Checklist

- Are there new checks included in this PR? No

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by MrCloudSec** [comment]
Hi @Jude-Bae, thanks for your contribution by adding on of the most important Korea’s security compliance frameworks!

@pedrooot will take care of this PR.

**Comment by MrCloudSec** [comment]
@Jude-Bae can you run our pre-commit and push the changes please?

You can install it by `pre-commit install`, thanks!

**Comment by Jude-Bae** [comment]
> @Jude-Bae can you run our pre-commit and push the changes please?
> 
> You can install it by `pre-commit install`, thanks!

Hi! @sergargar,

Thanks for the feedback! I’m currently commuting to work, but I’ll run the pre-commit checks and push the changes as soon as I’m at my desk. I’ll aim to get this done as quickly as possible.

**Comment by pedrooot** [comment]
Hey! @Jude-Bae first of all, thanks for your contribution. 

Prowler dashboards will be deprecated, soon just to let you know because you added some changes there.

Could you please fix the tests? Thanks!!

**Comment by Jude-Bae** [comment]
> Hey! @Jude-Bae first of all, thanks for your contribution.
> 
> Prowler dashboards will be deprecated, soon just to let you know because you added some changes there.
> 
> Could you please fix the tests? Thanks!!

Hi! @pedrooot Thanks for the heads-up regarding the dashboard changes! I’ll make sure to address the tests as soon as possible

**Comment by Jude-Bae** [comment]
Hi @pedrooot,

I’ve updated the branch with the latest changes and also added the test cases you suggested earlier. However, the status checks are still showing as “Expected — Waiting for status to be reported.” Could you let me know if there’s anything I might have missed or if I need to follow any additional steps?

If necessary, please advise if I should consider reopening the PR or take any other action to resolve this.
Thanks again for your help!

**Comment by pedrooot** [comment]
I just had to accept the re-run of the checks. Thanks for all the info! I'll review this PR later today.

**Comment by Jude-Bae** [comment]
Hi! @pedrooot,

I would like to address the situation regarding the Codecov report for the current PR. The low patch coverage percentage for the kisa_ismsp.py file seems to be a primary factor, but I have noticed that similar compliance files also report a patch coverage of 7 to 10%.

Could you please advise if I need to write additional test code for "kisa_ismsp.py" and similar files to improve coverage?
I have attached screenshots of the Codecov HTML report for reference.

If there are any additional steps I should take to facilitate the merging process, please let me know. 

SCR-20240924-bepx
SCR-20240924-bdsv
SCR-20240924-bdnn
SCR-20240924-bdfw
Thank you for your guidance!

**Comment by pedrooot** [comment]
Thank you for the report. For now, I don't need you to add more tests to this PR because I need to review it in depth to check how it works. As you can see, the percentage of tests associated with each compliance is similar to what you've obtained, so it should be correct 🔝

**Comment by pedrooot** [comment]
If I need anything else I'll ping you, thanks in advance

**Comment by pedrooot** [comment]
After reviewing the dashboard generated with this compliance, the numbers on the pass/fail bar are not appearing. Could you check how it works with other compliances? I'll show you the CIS example:

Screenshot 2024-09-23 at 18 05 31

Screenshot 2024-09-23 at 18 07 30

**Comment by Jude-Bae** [comment]
Hello! @pedrooot
Thank you for your prompt and thorough feedback! 
I have addressed the issue with the pass/fail numbers on the compliance dashboard and tested the fix with both the Korean and English versions of the KISA ISMS-P compliance. 

Please find the attached screenshots of both compliance versions dashboards showing the corrected pass/fail numbers. 

I have pushed the changes, and would appreciate it if you could kindly review and check again. Let me know if there is anything else I can improve or assist with. I truly appreciate your guidance and support!

SCR-20240924-dvwz
SCR-20240924-dsgq

**Comment by Jude-Bae** [comment]
Hi! @pedrooot, 

I hope you’re doing well. I’ve made some updates and resolved the issues in the code. I’d appreciate it if you could take a moment to review the changes when you have a chance. Your feedback would mean a lot to me.

Thanks for your support!

**Comment by pedrooot** [comment]
@Jude-Bae The last thing I’d like to ask is for you to rename the compliance names to match the format followed by the others, which would be changing '-' to '_': 
`kisa_isms-p_2023_aws` -> `kisa_isms_p_2023_aws`
`kisa_isms-p_2023-korean_aws` -> `kisa_isms_p_2023_korean_aws`

Thank you in advance! As soon as these changes are made, I will approve this PR and we’ll include the code in our latest release. :)

**Comment by Jude-Bae** [comment]
@pedrooot Updated the compliance file names **kisa_isms-p_2023_aws.json** and **kisa_isms-p_2023-korean.json** to **kisa_isms_p_2023_aws.json** and **kisa_isms_p_2023_korean_aws.json**, respectively, to align with the standard format. Accordingly, the related dashboard files **dashboard/compliance/kisa_isms_p_2023_aws.py** and **dashboard/compliance/kisa_isms_p_2023_korean_aws.py** have also been renamed.

I have also performed a self-check on the output and dashboard after these modifications. Below are the relevant screenshots for your reference.

Thank you again for your quick and accurate feedback throughout this process. **Your support has been invaluable, and I truly appreciate the help!"**

image

**Review by pedrooot — APPROVED** [review]
@Jude-Bae  Thanks a ton for the PR! 🎉 Really appreciate you taking the time to contribute, and your changes look awesome. Keep up the great work! 🚀 
❤️ From Prowler team

**Comment by Jude-Bae** [comment]
@pedrooot !!
Thank you so much for your kind words and encouragement! 🙏 It’s been an incredible honor for both myself and our team to contribute to such a widely-used and impactful open-source project that serves so many security professionals around the world.
 We are truly thrilled that the changes were well-received, and we look forward to continuing our contributions and working alongside the amazing Prowler team in the future!! 🚀

**Pull request merged**
