### PR TITLE
fix(mutelist): set arguments while loading providers

### LINKED ISSUE #5650: AWS MuteList broken
### Steps to Reproduce

**What command are you running:**

```bash
prowler aws -M json-ocsf -f us-west-2 -w mutelist.yaml --ignore-exit-code-3
```

**Cloud provider you are launching:** AWS

**Environment you have:**

* Single account
* Prowler open source
* Issues with:
  * Prowler installed via Pip
  * Prowler Container
* Prowler Version: 4.5.0 or 4.6.0

**Error:**

```
Something went wrong in accessanalyzer_enabled, please use --log-level ERROR

2024-11-06 20:26:48,299 [File: check.py:617] 	[Module: check]	 ERROR: accessanalyzer_enabled -- AttributeError[33]: 'str' object has no attribute 'get'
Something went wrong in appstream_fleet_maximum_session_duration, please use --log-level ERROR

2024-11-06 20:26:49,877 [File: check.py:617] 	[Module: check]	 ERROR: appstream_fleet_maximum_session_duration -- AttributeError[12]: 'str' object has no attribute 'get'
Something went wrong in appstream_fleet_session_disconnect_timeout, please use --log-level ERROR

2024-11-06 20:26:49,880 [File: check.py:617] 	[Module: check]	 ERROR: appstream_fleet_session_disconnect_timeout -- AttributeError[12]: 'str' object has no attribute 'get'
Something went wrong in appstream_fleet_session_idle_disconnect_timeout, please use --log-level ERROR

2024-11-06 20:26:49,884 [File: check.py:617] 	[Module: check]	 ERROR: appstream_fleet_session_idle_disconnect_timeout -- AttributeError[12]: 'str' object has no attribute 'get'
Something went wrong in autoscaling_find_secrets_ec2_launch_configuration, please use --log-level ERROR

2024-11-06 20:26:50,400 [File: check.py:617] 	[Module: check]	 ERROR: autoscaling_find_secrets_ec2_launch_configuration -- AttributeError[16]: 'str' object has no attribute 'get'
Something went wrong in awslambda_function_no_secrets_in_code, please use --log-level ERROR

2024-11-06 20:26:51,828 [File: check.py:617] 	[Module: check]	 ERROR: awslambda_function_no_secrets_in_code -- AttributeError[13]: 'str' object has no attribute 'get'
Something went wrong in awslambda_function_no_secrets_in_variables, please use --log-level ERROR

2024-11-06 20:26:51,832 [File: check.py:617] 	[Module: check]	 ERROR: awslambda_function_no_secrets_in_variables -- AttributeError[11]: 'str' object has no attribute 'get'
```
More errors follow...

### Expected behavior

Prowler will scan the AWS account and mute findings in the mutelist

### Actual Result with Screenshots or Logs

Prowler scans, but the above errors are displayed and no findings are muted.

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

EKS
Local

### OS used

EKS: `toniblyx/prowler:latest` Docker image
Local: macOS 14.7 Python 3.11

### Prowler version

Prowler 4.6.0

### Pip version

24.0

### Context

_No response_

### PR DESCRIPTION
**Pull request by thomscode**
### Context

Fixes #5650 

### Description

Mutelist files were not being loaded into the proper parameter in their providers. This change adds keyword args for the `config_path` and `mutelist_path` parameters so the arguments are added properly.

### Checklist

- Are there new checks included in this PR? No
- [ ] Review if the code is being covered by tests.
- [ ] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [ ] Review if backport is needed.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jfagoagas** [comment]
@thomscode I'm going to work on this right now. Thank you for reporting this.

**Comment by jfagoagas** [comment]
@thomscode could you please give me permissions to push to your branch? If that's not possible, please apply the following `patch` in your branch to prevent this from happening again while using other provider's arguments:
```patch
diff --git a/prowler/providers/common/provider.py b/prowler/providers/common/provider.py
index aef7c63fb..4e86ad42b 100644
--- a/prowler/providers/common/provider.py
+++ b/prowler/providers/common/provider.py
@@ -161,52 +161,52 @@ class Provider(ABC):
             if not isinstance(Provider._global, provider_class):
                 if "aws" in provider_class_name.lower():
                     provider_class(
-                        arguments.aws_retries_max_attempts,
-                        arguments.role,
-                        arguments.session_duration,
-                        arguments.external_id,
-                        arguments.role_session_name,
-                        arguments.mfa,
-                        arguments.profile,
-                        set(arguments.region) if arguments.region else None,
-                        arguments.organizations_role,
-                        arguments.scan_unused_services,
-                        arguments.resource_tag,
-                        arguments.resource_arn,
+                        retries_max_attempts=arguments.aws_retries_max_attempts,
+                        role_arn=arguments.role,
+                        session_duration=arguments.session_duration,
+                        external_id=arguments.external_id,
+                        role_session_name=arguments.role_session_name,
+                        mfa=arguments.mfa,
+                        profile=arguments.profile,
+                        regions=set(arguments.region) if arguments.region else None,
+                        organizations_role_arn=arguments.organizations_role,
+                        scan_unused_services=arguments.scan_unused_services,
+                        resource_tags=arguments.resource_tag,
+                        resource_arn=arguments.resource_arn,
                         config_path=arguments.config_file,
                         mutelist_path=arguments.mutelist_file,
                         fixer_config=fixer_config,
                     )
                 elif "azure" in provider_class_name.lower():
                     provider_class(
-                        arguments.az_cli_auth,
-                        arguments.sp_env_auth,
-                        arguments.browser_auth,
-                        arguments.managed_identity_auth,
-                        arguments.tenant_id,
-                        arguments.azure_region,
-                        arguments.subscription_id,
+                        az_cli_auth=arguments.az_cli_auth,
+                        sp_env_auth=arguments.sp_env_auth,
+                        browser_auth=arguments.browser_auth,
+                        managed_identity_auth=arguments.managed_identity_auth,
+                        tenant_id=arguments.tenant_id,
+                        region=arguments.azure_region,
+                        subscription_ids=arguments.subscription_id,
                         config_path=arguments.config_file,
                         mutelist_path=arguments.mutelist_file,
                         fixer_config=fixer_config,
                     )
                 elif "gcp" in provider_class_name.lower():
                     provider_class(
-                        arguments.organization_id,
-                        arguments.project_id,
-                        arguments.excluded_project_id,
-                        arguments.credentials_file,
-                        arguments.impersonate_service_account,
-                        arguments.list_project_id,
+                        organization_id=arguments.organization_id,
+                        project_ids=arguments.project_id,
+                        excluded_project_ids=arguments.excluded_project_id,
+                        credentials_file=arguments.credentials_file,
+                        impersonate_service_account=arguments.impersonate_service_account,
+                        list_project_ids=arguments.list_project_id,
                         config_path=arguments.config_file,
                         mutelist_path=arguments.mutelist_file,
                         fixer_config=fixer_config,
                     )
                 elif "kubernetes" in provider_class_name.lower():
                     provider_class(
-                        arguments.kubeconfig_file,
-                        arguments.context,
-                        arguments.namespace,
+                        kubeconfig_file=arguments.kubeconfig_file,
+                        context=arguments.context,
+                        namespace=arguments.namespace,
                         config_path=arguments.config_file,
                         mutelist_path=arguments.mutelist_file,
                         fixer_config=fixer_config,
```

Thank you!

**Comment by thomscode** [comment]
@jfagoagas,
I added you as a collaborator to my fork.

**Review by jfagoagas — APPROVED** [review]
Thanks for the fix 🚀

**Pull request merged**
